### ISSUE TITLE
Implement concurrent hash table for _FSR_keys_map

### ISSUE THREAD

**Issue by samuelshaner** [mit-crpg/OpenMOC#101]
The segmentation routines do not currently support concurrent reading and writing to the `_FSR_keys_map`. In order to support parallel segmentation, a concurrent hash table should be implemented for the `_FSR_keys_map` to avoid errors  in the `Geometry` `findFSRId` routine during segmentation.

**Comment by geogunow** [comment]
This issue is solved by the Parallel Hash Map PR. This issue should be closed once the PR is merged.

**Comment by geogunow** [comment]
This was solved in #157
