### ISSUE TITLE
Test version of the DRAGON compatibility module 

### ISSUE THREAD

**Issue by augusto-vib** [mit-crpg/OpenMOC#110]
The first test release of DRAG_OpenMOC is under the DRAGON branch in a tar file. Although it works fine, it needs to be changed to object oriented and written in a style that matches the OpenMOC development syntax. More realistic test cases need to be added as well. I just applied to get the International Handbook of Evaluated Criticality Safety Benchmark Experiments in order to pursue the DRAG_OpenMOC validation in the future.

**Comment by wbinventor** [comment]
Closed per the lack of development on PR #114.
