### ISSUE TITLE
Universe function getAllUniverses does not include current universe

### ISSUE THREAD

**Issue by samuelshaner** [mit-crpg/OpenMOC#124]
When trying to run a pin cell problem with only one universe (the root universe) and trying to divide the fuel into rings and sectors and moderator into sectors, rings and sectors are not created. In the `Geometry::subdivideCells` method, the `Universe::getAllUniverses` method is called on the root universe. This function will return an empty map so the pin cell will not be broken up into rings and sectors. This could be fixed by adding the following line to the `Universe::getAllUniverses` method:

`universes[_id] = this;`

**Comment by wbinventor** [comment]
@samuelshaner is this a bug you plan to take care of in a future PR?

**Comment by samuelshaner** [comment]
Yes, I'll take care of it. I'll get to it next week.

**Comment by wbinventor** [comment]
Fixed in PR #126.
