### ISSUE TITLE
Optimize VectorizedSolver class

### ISSUE THREAD

**Issue by wbinventor** [mit-crpg/OpenMOC#15]
The VectorizedSolver class (and its child VectorizedPrivateSolver) are inordinately slower than the non-vectorized solvers. This class should be faster than the corresponding CPUSolver and ThreadPrivateSolver classes, but it is not. We need to use PAPI profiling to figure out the percentage of vector instructions to total instructions issued, and determine what the bottleneck on performance is.

**Comment by geogunow** [comment]
Wasn't this issue solved by @theshuo after fixing the false sharing issue?

**Comment by wbinventor** [comment]
No - that was a separate issue. @theshuo figured out how to make the old
``CPUSolver`` with mutual exclusion scale as well in multi-core as the old
``ThreadPrivateSolver`` without mutual exclusion but at the sake of private
FSR scalar flux arrays.

This issue pertains to the ``VectorizedSolver`` which is built when using
the Intel compiler. I wrote this code whole at ANL in 2013 as an attempt to
SIMD vectorize the innermost loops over energy and polar angles using
Intel's auto-vectorization pragmas and the MKL/VML. This code is fully
functional, but does not see a performance boost over the plain vanilla
``CPUSolver``. I had hoped that yours and @johntramm's work to vectorize
SimpleMOC might translate well to the ``VectorizedSolver`` someday, but
that might not be practical until we have higher order sources.

**Comment by GiudGiud** [comment]
The standard CPUSolver is now SIMD vectorized as well (3D MOC branch)
To address this issue, line by line profiling should help to figure out what's slow.
Closing this issue since no one is working on the VectorizedSolver anymore
