### ISSUE TITLE
CMFD initialization should be just prior to track generation

### ISSUE THREAD

**Issue by samuelshaner** [mit-crpg/OpenMOC#170]
Currently the CMFD object is initialized in `Geometry::initializeFlatSourceRegions()`, but after this method is called, the user has the ability to change the boundary conditions. A change of the boundary conditions after `Geometry::initializeFlatSourceRegions()`, but prior to `TrackGenerator::generateTracks()` is called would result in a mismatch in the BCs in the MOC and CMFD problems. To fix this issue, the `Geometry::initializeCmfd()` method should be called within `TrackGenerator::generateTracks()` (or one of the methods called by this method) instead of in `Geometry::initializeFlatSourceRegions()`.

**Comment by wbinventor** [comment]
Fixed in #172.
