### ISSUE TITLE
Cell::get___BoundaryType() and Cell::getMax_()/Cell::getMin_()  should compute values

### ISSUE THREAD

**Issue by samuelshaner** [mit-crpg/OpenMOC#171]
The `Cell::get___BoundaryType()` and `Cell::getMax_()`/`Cell::getMin_()` methods use values that are set from the `Cell::findBoundingBox()` routine any time a surface is added or removed from a cell. If attributes of the surface (e.g. the boundary condition or CSG attributes) are changed, these changes will not be immediately reflected in the cell. To avoid any potential conflicts between the values computed in the `Cell::findBoundingBox()` method and actual values based on the surfaces comprising the cell, the min/max values and boundary conditions should be computed each time they are queried.

**Comment by wbinventor** [comment]
Fixed in #173.
