### ISSUE TITLE
Multicore Scaling

### ISSUE THREAD

**Issue by jtramm** [mit-crpg/OpenMOC#191]
Geoff and I noticed some scaling issues on multicore architectures with some of the current test cases. C5G7 seems to be hitting a wall after only a few cores are added (see speedup data below). We had originally suspected that it may be only the CMFD that was causing the issue, but even without it there still may be some opportunities for optimizations here. I'm going to dig into this and see if I can't find some ways of optimizing things -- I just wanted to put this data up to see if others had seen similar results.

![sandybridge](https://cloud.githubusercontent.com/assets/1009059/9064336/ab6604f0-3a91-11e5-876d-ad66b865defe.jpg)
![haswell](https://cloud.githubusercontent.com/assets/1009059/9064337/ab72681c-3a91-11e5-8b51-f6417ec21be7.jpg)

**Comment by samuelshaner** [comment]
@jtramm - Is this weak or strong scaling? Also, how many angles and spacing were you using?

**Comment by wbinventor** [comment]
Looks like @samuelshaner asked the same questions I planned to ask? This is
not the scaling that I saw in my scaling studies a year and a half ago.

**Comment by jtramm** [comment]
This is strong scaling. It was the c5g7 and c5g7-cmfd  benchmarks (running default parameters) in profile/models/c5g7

**Comment by wbinventor** [comment]
Well that is your problem :-) You're not exposing enough work for 16 or 36 cores. The default parameters are 4 azimuthal angles and 0.1 cm track spacing. Try re-running these studies with (max(# threads) x 4) angles and you should see the near perfect scaling I reported two years ago.

**Comment by wbinventor** [comment]
I might mention that 4 angles isn't a "target problem size" anyway, while something like 36 x 4 = 144 angles is closer to the standard angular discretization in industrial 2D MOC codes. All this being said, if you do some profiling and figure out some ways to speed up the code further, then by all means go for it!

**Comment by geogunow** [comment]
@wbinventor I agree that the problem size is small, but remember that we are parallelizing over tracks, not just angles in the current form of OpenMOC. Therefore I would not expect this poor of scaling on C5G7 - even with the coarse track laydown.

**Comment by wbinventor** [comment]
This has always been the case. I think with a good implementation of
finer-grained parallelism you might be able to achieve better results. But
what you are seeing is well documented in my thesis and papers on this
topic.

On Tue, Aug 4, 2015 at 9:11 AM, Geoffrey Gunow <notifications@github.com>
wrote:

> @wbinventor <https://github.com/wbinventor> I agree that the problem size
> is small, but remember that we are parallelizing over tracks, not just
> angles in the current form of OpenMOC. Therefore I would not expect this
> poor of scaling on C5G7 - even with the coarse track laydown.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mit-crpg/OpenMOC/issues/191#issuecomment-127661698>.
>



-- 
Will Boyd
Nuclear Science & Engineering
Massachusetts Institute of Technology
Cell: 423.413.8469
wbinventor@gmail.com

**Comment by jtramm** [comment]
With 144 azimuthal angles, I'm still getting very similar results:

![many_angles](https://cloud.githubusercontent.com/assets/1009059/9066345/9f69efe4-3a9c-11e5-8fbe-4e1ab422b6ec.jpg)

**Comment by samuelshaner** [comment]
Cmfd might still have relatively poor scaling results since the functions have not been rigorously tuned to scale well beyond a few cores. You might try to run the cases without cmfd and I would expect the calling would be better.

**Comment by wbinventor** [comment]
Yes, I don't find this surprising at all since CMFD has not been optimized
for OpenMP. At some point the time spent in CMFD will dwarf the time spent
in the parallel MOC and Amdahl's Law will come back to bite. Try without
CMFD and let us know what you see.

On Tue, Aug 4, 2015 at 9:41 AM, sam <notifications@github.com> wrote:

> Cmfd might still have relatively poor scaling results since the functions
> have not been rigorously tuned to scale well beyond a few cores. You might
> try to run the cases without cmfd and I would expect the calling would be
> better.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mit-crpg/OpenMOC/issues/191#issuecomment-127669086>.
>



-- 
Will Boyd
Nuclear Science & Engineering
Massachusetts Institute of Technology
Cell: 423.413.8469
wbinventor@gmail.com

**Comment by jtramm** [comment]
The performance without CMFD at 144 azimuthal angles is definitely a lot more reasonable, though I think there still may potentially be room for some optimization. I think the ceiling should be somewhere around 20-25x speedup at 36 cores, and we're at 16.6 right now. 

![many angles no cmfd](https://cloud.githubusercontent.com/assets/1009059/9071770/d12e752a-3abc-11e5-82b5-4f922e078606.jpg)

**Comment by wbinventor** [comment]
Great, glad you are seeing more reasonable results. The speedup still isn't
as what I observed on machines with fewer cores, so perhaps the performance
has changed as the code has evolved since then. Just curious - when you
compute "speedup" here, are you looking at the total runtime, or are you
normalizing to the number of segments and iterations? The number of
segments does not change linearly with the number of angles, though it is
within a few percent of a linear model, and the number of iterations will
vary slightly with the number of angles (if you are fully converging). As
long as you normalize the runtime to both of these then you should be
computing an accurate speedup metric.

On Tue, Aug 4, 2015 at 1:28 PM, John Tramm <notifications@github.com> wrote:

> The performance without CMFD at 144 azimuthal angles is definitely a lot
> more reasonable, though I think there still may potentially be room for
> some optimization. I think the ceiling should be somewhere around 20-25x
> speedup at 36 cores, and we're at 16.6 right now.
>
> [image: many angles no cmfd]
> <https://cloud.githubusercontent.com/assets/1009059/9071770/d12e752a-3abc-11e5-82b5-4f922e078606.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mit-crpg/OpenMOC/issues/191#issuecomment-127749538>.
>



-- 
Will Boyd
Nuclear Science & Engineering
Massachusetts Institute of Technology
Cell: 423.413.8469
wbinventor@gmail.com

**Comment by jtramm** [comment]
In the timing report:

[  TITLE  ]  *******************************************************************
[  TITLE  ]                             TIMING REPORT
[  TITLE  ]  *******************************************************************
[  RESULT ]  Total time to solution...............................2.7983E+02 sec
[  RESULT ]  Solution time per iteration..........................4.4138E-01 sec
[  RESULT ]  Integration time per segment integration.............4.9010E-10 sec

I'm using the "Total time to solution" metric. I'm not sure I understand what you mean by normalizing in this context. Since this is strong scaling, the only thing I'm altering is the number of threads I specify. All other things regarding the computation (angles, segments, iterations) should be identical for all runs.

**Comment by wbinventor** [comment]
Oh sorry, I forgot this is strong rather than weak scaling!

**Comment by wbinventor** [comment]
@jtramm do you still consider this an issue? The performance isn't quite as
good as what I observed before, but this is strong scaling on a machine
with 3x the cores.

**Comment by jtramm** [comment]
I'm in the process of putting a number of small optimizations together. We can close this issue and I'll put in a PR when I have it ready.
