### ISSUE TITLE
Compute the CMFD surface diffusion coefficients on-the-fly

### ISSUE THREAD

**Issue by samuelshaner** [mit-crpg/OpenMOC#211]
Currently, the materials have surface diffusion coefficients (`_dif_hat` and `_dif_tilde`) for each energy group and surface of a cmfd cell. Materials for the MOC problem don't need these variables and they don't really represent material properties - they are intermediate terms used in setting up the diffusion matrices. I would recommend we change the `Cmfd::computeDs(int moc_iteration)` to two new methods:

- `Cmfd::computeSurfaceDiffusionCoefficient(int cmfd_cell, int surface)` - Compute the surface diffusion coefficient based on the boundary conditions and diffusion coefficients in the neighboring cells.
- `Cmfd::computeSurfaceDiffusionCoefficientCorrection(int cmfd_cell, int surface, int moc_iteration)` - Compute the surface diffusion coefficient correction based on the surface currents tallied during the last MOC iteration, the boundary conditions, and the surface diffusion coefficient for the given cmfd cell and surface.

**Comment by wbinventor** [comment]
I like this idea a lot - the slimmer we can make the `Material` class the better in my opinion. We don't need to give the user a front-facing API to get/set diffusion coefficients for CMFD anyway, so computing them on the fly seems like a cleaner approach.

**Comment by wbinventor** [comment]
On a related note, I think CMFD should compute sigma_a on-the-fly as well. The absorption cross-section isn't used anywhere else in the code, and could be gutted from the ``Material``. In addition, when using scattering matrices that account for neutron multiplication it isn't appropriate to the use the standard sigma_ but rather sigma_t - sum(sigma_s), which I think is one reason I've seen some instabilities when using CMFD with my MC-generated MGXS.

**Comment by wbinventor** [comment]
Closed with #216.
