### ISSUE TITLE
logger errors out on long TITLE and HEADER strings

### ISSUE THREAD

**Issue by samuelshaner** [mit-crpg/OpenMOC#229]
OpenMOC errors out when a `TITLE` log level is used with a string of `length > line_length - 4` and when a `HEADER` log level is used with a string of `length > line_length - 1`.

For the logger, I would be in favor of not having an explicit line length limitation for any log level type and just having procedures to extend each log level string to multiple lines. For instance, TITLE might be extended to something like:

```
[   TITLE   ]   ****************************************************************
[   TITLE   ]       THIS IS A VERY, VERY, VERY, VERY, VERY, VERY, VERY, VERY,
[   TITLE   ]      VERY, VERY, VERY, VERY, VERY, VERY, VERY, VERY, VERY, VERY,
[   TITLE   ]      VERY, VERY, VERY, VERY, VERY, VERY, VERY, VERY, VERY, VERY,
[   TITLE   ]                            VERY LONG TITLE                                    
[   TITLE   ]   ****************************************************************
```

and HEADER might be extended to something like:

```
[   HEADER  ]   ***  THIS IS A VERY, VERY, VERY, VERY, VERY, VERY, VERY, VERY,  ***
[   HEADER  ]   *****  VERY, VERY, VERY, VERY, VERY, VERY, VERY, VERY, VERY,  *****
[   HEADER  ]   *****  VERY, VERY, VERY, VERY, VERY, VERY, VERY, VERY, VERY,  *****
[   HEADER  ]   **********************  VERY LONG HEADER  *************************                                    
```

While the TITLE and HEADER are not that pretty, I would rather see an ugly (but legible) string than an error because a HEAER or TITLE string is too long.

**Comment by GiudGiud** [comment]
Addressed by PR #331, closing
