### ISSUE TITLE
CMFD convergence with fine track laydown and single precision

### ISSUE THREAD

**Issue by wbinventor** [mit-crpg/OpenMOC#233]
I've noticed an issue with the convergence of CMFD for some problems I've been running lately. In particular, it appears to have trouble converging when I use a very fine track laydown coupled with a tight convergence tolerance - *e.g.*, 128 angles and 0.01 cm spacing with a 1E-7 convergence threshold on the fission source. The convergence is *only* an issue when the code is compiled using single precision and is *not* an issue with double precision. 

In particular, for a 2-group assembly problem with double precision I see the following convergence when using the fine track laydown and tight convergence threshold specified above:

```bash
[  NORMAL ]  Iteration 0:	k_eff = 1.037898	res = 1.287E-316
[  NORMAL ]  Iteration 1:	k_eff = 1.041340	res = 1.198E-01
[  NORMAL ]  Iteration 2:	k_eff = 1.041596	res = 2.345E-02
[  NORMAL ]  Iteration 3:	k_eff = 1.041644	res = 1.597E-02
[  NORMAL ]  Iteration 4:	k_eff = 1.041643	res = 1.538E-03
[  NORMAL ]  Iteration 5:	k_eff = 1.041643	res = 5.958E-04
[  NORMAL ]  Iteration 6:	k_eff = 1.041644	res = 1.667E-04
[  NORMAL ]  Iteration 7:	k_eff = 1.041644	res = 4.505E-05
[  NORMAL ]  Iteration 8:	k_eff = 1.041644	res = 2.328E-05
[  NORMAL ]  Iteration 9:	k_eff = 1.041644	res = 3.888E-06
[  NORMAL ]  Iteration 10:	k_eff = 1.041644	res = 2.678E-06
[  NORMAL ]  Iteration 11:	k_eff = 1.041644	res = 5.135E-07
[  NORMAL ]  Iteration 12:	k_eff = 1.041644	res = 2.444E-07
```

However, when using single precision the convergence appears as follows :

```bash
[  NORMAL ]  Iteration 0:	k_eff = 1.037898	res = 0.000E+00
[  NORMAL ]  Iteration 1:	k_eff = 1.041347	res = 1.182E-01
[  NORMAL ]  Iteration 2:	k_eff = 1.041608	res = 2.504E-02
[  NORMAL ]  Iteration 3:	k_eff = 1.041644	res = 1.642E-02
[  NORMAL ]  Iteration 4:	k_eff = 1.041643	res = 1.584E-03
[  NORMAL ]  Iteration 5:	k_eff = 1.041644	res = 6.078E-04
[  NORMAL ]  Iteration 6:	k_eff = 1.041643	res = 1.611E-04
[  NORMAL ]  Iteration 7:	k_eff = 1.041643	res = 4.029E-05
[  NORMAL ]  Iteration 8:	k_eff = 1.041643	res = 2.264E-05
[  NORMAL ]  Iteration 9:	k_eff = 1.041643	res = 3.759E-06
[  NORMAL ]  Iteration 10:	k_eff = 1.041643	res = 2.889E-06
[  NORMAL ]  Iteration 11:	k_eff = 1.041643	res = 1.054E-06
[  NORMAL ]  Iteration 12:	k_eff = 1.041643	res = 6.879E-07
[  NORMAL ]  Iteration 13:	k_eff = 1.041643	res = 1.137E-06
[  NORMAL ]  Iteration 14:	k_eff = 1.041643	res = 8.390E-07
[  NORMAL ]  Iteration 15:	k_eff = 1.041642	res = 6.607E-07
[  NORMAL ]  Iteration 16:	k_eff = 1.041643	res = 9.157E-07
[  NORMAL ]  Iteration 17:	k_eff = 1.041644	res = 7.292E-07
[  NORMAL ]  Iteration 18:	k_eff = 1.041643	res = 1.277E-06
[  NORMAL ]  Iteration 19:	k_eff = 1.041643	res = 2.033E-06
[  NORMAL ]  Iteration 20:	k_eff = 1.041644	res = 1.731E-06
[  NORMAL ]  Iteration 21:	k_eff = 1.041643	res = 1.505E-06
```

Perhaps the roundoff error that accumulates when computing group constants from a very fine track laydown. Although I'm not intimately familiar with CMFD, my guess is that we might need to employ pairwise sums in some places to counter the roundoff error in accumulators, similar to what we found was needed in the MOC solver to solve full-core problems two years ago.

This is very clearly a low priority issue, but I wanted to make note of it here for posterity. It is nice to run problems in single precision - especially large problems with lots of energy groups - to keep a damper on the memory footprint. So this might be an issue to attack in the future to make these problems tractable on machines with reasonable amounts of memory.

**Comment by samuelshaner** [comment]
Thanks for pointing out this issue @wbinventor. I've used pointwise sums throughout the linear algebra files so I don't think this should be the issue. I've found one issue with CMFD that I'll submit a PR on later today.

There are also a few other items to keep in mind. For a given residual convergence for the MOC solve, running the problem with CMFD will result in much tighter convergence on the requested convergence parameter than running the problem without CMFD. Also, the unaccelerated MOC problem will eventually reach a point where it cannot be converged any tighter and for single precision on the problem you mentioned that is right around 1e-7.

One area where the pairwise sum could help, but might be difficult, is in summing the contribution of each track to the CMFD cell surface currents. For a fine track laydown there can be a lot of crossings and the iteration-to-iteration change in the tallied surface currents might be significant.

**Comment by wbinventor** [comment]
Yeah I wondered if the surface current tallying might contribute to the roundoff error. Thanks for clarifying the convergence criteria, I think I'll just relax my criteria when I use CMFD and/or use double precision. This is probably just fine for now, but this sort of thing might creep back up and be an issue as we scale up to full-core 3D problems.

On a side note, if this issue is related to the tallied surface currents, then I think this doesn't bode well for the roundoff error one would observe in tallies in a monte carlo code (without some sort of buffered pairwise sum for tally accumulation).

**Comment by wbinventor** [comment]
Closing this since we determined that this is simply due to roundoff error with single precision.
