### ISSUE TITLE
Allocation and Deallocation of Point Coordinates

### ISSUE THREAD

**Issue by geogunow** [mit-crpg/OpenMOC#241]
In the `Point` class, the underlying data is `_xyz` which is an array storing the x, y, and z coordinates. This variable is stored as a `double*` with the memory being allocated in the constructor and deallocated in the destructor.  This is inefficient because of all the memory allocation and deallocation calls. Instead, `_xyz` should be stored as `double[3]` since it is always 3 elements long. This alternative definition would be much faster since no dynamic memory allocation would be required.

**Comment by GiudGiud** [comment]
closed with #431
