### ISSUE TITLE
OpenMOC fails when ZCylinders extend outside geometry boundaries 

### ISSUE THREAD

**Issue by samuelshaner** [mit-crpg/OpenMOC#269]
If someone creates a cell with a zcylinder that extends outside the geometry boundary, OpenMOC will have the bounding box of the universe that contains the cells to extend out to the greatest radius zcylinder with a `-1` halfspace. The picture below shows a case where OpenMOC would fail. OpenMOC would create a bounding box shown in green for the root universe and create tracks that extend out to that bounding box. The tracks would all fail to find a first cell.

![pin_fail](https://cloud.githubusercontent.com/assets/1244537/13085010/1f9f08b4-d4aa-11e5-8c3a-543ea26cd4d1.png)

The peculiar thing about this issue is that we don't see it when we use ringify to create rings that extend outside the geometry bounds. This is because ringify is called *after* the tracks have been created. 

The fix to this issue seems tricky. I think it would require restructuring the way the geometry computes the min/max x/y/z values to be aware of the surfaces that are boundaries. Perhaps a `Geometry::getBoundingSurfaces()` method. Then the bounding surfaces would need to be checked to get the geometry min/max x/y/z values.

While this issue might seem esoteric, I think it will be relevant to any multi-sim cases where surfaces are created that extend outside the geometry boundaries. For instances, if @friedmud's example from PR #268 generated tracks a second time, I *think* it would fail.

**Comment by wbinventor** [comment]
Can we simply query only those surfaces with REFLECTIVE, PERIODIC, or
VACUUM BCs when we build the bounding box? Rather than include the
INTERFACE ZCylinder? I thought that we enforced this a long time ago but
perhaps things had changed.

**Comment by samuelshaner** [comment]
If this was done, then all cells in the geometry that did not have valid bounding surfaces would have an infinite bounding box. Do you know if the bounding box is used for anything else other than getting the geometry min/max values? If not, then this would not be a problem.

**Comment by samuelshaner** [comment]
Looking at the code, I don't think the `Cell::findBoundingBox()` method is really needed at all. I believe all that is needed is:

* **Geometry::getBoundingSurfaces()`**: Get all the bounding surfaces for cells in the root universe. 
* **Restructure Geometry::getMax_() and Geometry::getMin_()**: Restructure these methods to get the bounding surfaces and report value for the correct boundary surface.

**Comment by wbinventor** [comment]
Closing with #271.
