### ISSUE TITLE
Feature request: CMFD-like spatial discretization

### ISSUE THREAD

**Issue by tjlaboss** [mit-crpg/OpenMOC#340]
For geometries other than cylinders, you can't use `Cell.setNumRings()` to refine your spatial discretization. When comparing results across codes, it is also useful to replicate a mesh tally over one's geometry.

Let's say my geometry looks like this:

<img src="https://user-images.githubusercontent.com/19986691/40750348-fc8822da-6434-11e8-8b35-de15f080729b.png" width=250>

*Figure 1: Unit cell geometry*

And that I want to split it up like so:

<img src="https://user-images.githubusercontent.com/19986691/40750350-fd745af6-6434-11e8-84c2-159c94849e22.png" width=250>

*Figure 2: 2x2 CMFD mesh*

This can currently be done with `cmfd.setLatticeStructure(nx, ny)`.

That's great if you want to set your CMFD mesh to exactly the mesh you use for FSR discretization; but for a fine mesh, that is **very slow**.

<img src="https://user-images.githubusercontent.com/19986691/40750600-ccfc7a92-6435-11e8-9de3-c91e5d1346ba.png" width=250>

*Figure 3: 8x8 mesh*

A feature that would be very helpful for me would be a function in the spirit of `Cell.setNumRings(n)`, e.g., `Cell.setMeshDivision(nx, ny)` -- something that produces the FSRs in Fig. 3 while using the mesh in Fig. 2 for CMFD.

I wonder if this could be implemented by passing a second instance of CMFD to [`Geometry::segmentize()`](https://github.com/mit-crpg/OpenMOC/blob/develop/src/Geometry.cpp#L864).

**Comment by tjlaboss** [comment]
Looks similar to https://github.com/mit-crpg/OpenMOC/issues/106: "Mask" object

**Comment by GiudGiud** [comment]
I just added this functionality in my branch.
Let me know how it compares to linear sources for your case

**Comment by tjlaboss** [comment]
That's `cartesianDivide()`? Awesome!

**Comment by tjlaboss** [comment]
Closed with #387.
