### ISSUE TITLE
Removing Python2 build from the test suite

### ISSUE THREAD

**Issue by GiudGiud** [mit-crpg/OpenMOC#383]
Just a heads up that this is coming in a future PR to 3D-MOC.
develop will follow

**Comment by tjlaboss** [comment]
Nice. Python 2 support was removed from OpenMC in 2018: https://github.com/openmc-dev/openmc/pull/965. Feel free to assign me when to the PR when it is ready.

**Comment by GiudGiud** [comment]
closed with #431
