### ISSUE TITLE
Does OpenMOC support running on multiple gpus or even multiple nodes?

### ISSUE THREAD

**Issue by lishunde** [mit-crpg/OpenMOC#421]
I tried running OpenMOC on a cluster, but found that it took longer, and the result seemed to be a separate run for each node.

**Comment by GiudGiud** [comment]
Hello

Only in the 3D-MOC branch, OpenMOC can run on multiple nodes using domain decomposition. It is achieved using distributed parallelism implemented with MPI. 

Use mpi4py to do that through the python API, or use the runtime_standard executable that you can compile with the Makefile in profile/

The examples in profile/models/ can guide you

Multi-GPU is currently not supported

Guillaume

**Comment by lishunde** [comment]
it helped me a lot ,thanks.
