### ISSUE TITLE
Error in GPUSolver

### ISSUE THREAD

**Issue by AI-Pranto** [mit-crpg/OpenMOC#469]
I got the following error while I was trying to run the c5g7 case problem with GPUSolver on [Google colab](https://drive.google.com/drive/u/0/folders/1xWqjhOrSHiylRx3VI3aWbAl_VIKEmtOi)

![openmoc](https://user-images.githubusercontent.com/49443884/102600561-30148000-4149-11eb-984d-a32183ccf3d3.png)

**Comment by GiudGiud** [comment]
This is a swig problem usually, when a derived class does not have implementations for all the functions it should have. 
Did you modify any of the Solver or GPUSolver files? 
Which CUDA version are you using?

**Comment by AI-Pranto** [comment]
@GiudGiud Basically, I was trying on Google Colab. Take a look [openmoc-run](https://colab.research.google.com/drive/1tq26f3TelnXuEJaP-fuoLDhQppI_HEpG#scrollTo=vhGTz3p9MUEe).

> Which CUDA version are you using?

![git](https://user-images.githubusercontent.com/49443884/102643871-219a8880-418a-11eb-88bf-368f0d75eafb.png)

**Comment by GiudGiud** [comment]
cuda 10.1 should be good enough. 
I'll take a look

**Comment by GiudGiud** [comment]
Ok I can confirm the issue. I was working last summer on the GPU CMFD solver. The GPU MOC solver was fixed in this work. You can look at the PR_CMFD_GPU branch on my fork.
I'll merge the fix when I'll add the CMFD GPU solver. 

Please leave the issue open in the mean time.

**Comment by GiudGiud** [comment]
Should be solved now, was some missing function declarations 
PR_CMFD_GPU branch is not ready, just use develop.

**Comment by AI-Pranto** [comment]
Thanks @GiudGiud! But still I see the same error `No constructor defined - class is abstract`
```bash
solver = GPUSolver(track_generator)
  File "/home/pranto/miniconda3/envs/openmc-openmoc/lib/python3.8/site-packages/openmoc/cuda/openmoc_cuda.py", line 392, in __init__
    raise AttributeError("No constructor defined - class is abstract")
AttributeError: No constructor defined - class is abstract
```
[input.zip](https://github.com/mit-crpg/OpenMOC/files/5830738/input.zip)

**Comment by GiudGiud** [comment]
This input runs fine for me.
Did you 'clean' the install before re-installing?
Can you paste the installation log?

If you can run nvcc there really should not be an issue though.

**Comment by AI-Pranto** [comment]
@GiudGiud After the reinstall, it runs here too. Thanks @GiudGiud
