### ISSUE TITLE
The result of the k calculation using OpenMOC diverged

### ISSUE THREAD

**Issue by David-sys-max** [mit-crpg/OpenMOC#485]
Hello everyone, since I can’t access the OpenMOC forum, I have to seek help here. When I use OpenMOC to verify the cross sections generated from OpenMC, I replaced rod elements with plate elements, and I noticed that the k calculation keeps diverging. However, if I set the energy groups to a very small number like casmo-70, k converges. Is this due to the specific nature of plate elements? Can anyone help me with this?Here is my input,Thank you![
![1718105653725](https://github.com/mit-crpg/OpenMOC/assets/172388592/08e7226b-9066-45ca-8f74-c64f1bcfc491)
![e4d069c074c4c9ae9aaa3c1eba4116e295b60dc8_2_572x499](https://github.com/mit-crpg/OpenMOC/assets/172388592/f2c1a34c-cdff-4b50-800c-9a7121b99aeb)

**Comment by GiudGiud** [comment]
Hello

I dont think there is an OpenMOC forum.
I dont think plate elements are a problem.
You may want to check the quality of your group cross sections libraries if you are tallying in a very fine energy structure. Your group cross sections are likely unconverged due to very thin bins. And wrong group cross sections, especially for the transport correction if you are using that, make convergence very difficult

**Comment by geogunow** [comment]
Hello David. Likely your transport corrected cross sections are making the problem fundamentally unstable unless dampening is applied. See my paper from 2019: “ Stabilization of multi-group neutron transport with transport-corrected cross-sections”

**Comment by David-sys-max** [comment]
> Hello你好
> 
> I dont think there is an OpenMOC forum.我不认为有OpenMOC论坛。 I dont think plate elements are a problem.我不认为板元素有问题。 You may want to check the quality of your group cross sections libraries if you are tallying in a very fine energy structure. Your group cross sections are likely unconverged due to very thin bins. And wrong group cross sections, especially for the transport correction if you are using that, make convergence very difficult如果您要计算非常精细的能量结构，您可能需要检查组横截面库的质量。由于箱非常薄，您的组横截面可能未收敛。错误的群横截面，特别是对于传输校正，如果你使用它，会使收敛变得非常困难
