### ISSUE TITLE
ModuleNotFoundError: No module named 'endf'

### ISSUE THREAD

**Issue by Worfran** [mit-crpg/OpenMOC#489]
I followed the installation process in the quick installation [guide,](https://docs.openmc.org/en/latest/quickinstall.html) but OpenMC is not recognized as a Python package. When I try to import it using Python in the terminal within the repository on my PC, I get the following error:

$ python
>>> import openmc
ModuleNotFoundError: No module named 'endf'

I am new to this type of coding and to using Linux. I would greatly appreciate any help.

![image](https://github.com/user-attachments/assets/3a2fe5da-3a12-4754-b5f1-0278af17f575)

![image](https://github.com/user-attachments/assets/8583040c-7ba6-423c-a0f1-4146ce54cfe8)

![image](https://github.com/user-attachments/assets/4005e3a3-2d10-4a69-aa29-30c42429a4f3)

**Comment by GiudGiud** [comment]
you have to add openmc to your PYTHONPATH for python to be able to find it

**Comment by Worfran** [comment]
Thank you for your help! Since I’m using an Arch Linux distribution, I couldn’t use pip install to install packages system-wide. I tried using pipx, but that didn’t work either. Instead, I created a Python virtual environment and installed the package using pip install, as explained in this [issue](https://github.com/pypa/pipx/issues/1533#issuecomment-2341137157).
