### ISSUE TITLE
Ray tracing input files from OpenCSG

### ISSUE THREAD

**Issue by wbinventor** [mit-crpg/OpenMOC#77]
Implement the ability to input a binary file of ray tracing data (ie, track segment lengths, region IDs, etc.) exported from OpenCSG.

**Comment by geogunow** [comment]
Should we rename this OpenCG?

**Comment by wbinventor** [comment]
Yes

**Comment by wbinventor** [comment]
Closing this since ray tracing in OpenCG has been relegated to a very low priority state.
