### ISSUE TITLE
Ray tracing breaks with large number of azimuthal angles

### ISSUE THREAD

**Issue by PrezNattyGibbs** [mit-crpg/OpenMOC#79]
Consider the pin-cell.py sample-input file.  If one uses the command line options "-s .01 -a 512", the code stops progressing at "Ray tracing for track segmentation...".  Memory usage slowly creeps up and up.

So it appears something breaks with this large number of angles (or perhaps large number of tracks).

**Comment by wbinventor** [comment]
This is no longer an issue due to refactorization of the ray tracing (PR #98) and the geometry (PR #112). I've run up to 16,384 angles for some of the simple sample input files (pin-cell, tiny-lattice, simple-lattice and nested-lattice) without an issue.
