### ISSUE TITLE
Build and validate 2D BEAVRS benchmark 

### ISSUE THREAD

**Issue by wbinventor** [mit-crpg/OpenMOC#9]
Create input files for the BEAVRS benchmark geometry at the axial-midplane. Use 2-group and 8-group cross-section data generated from CASMO for the materials.

This issue will require fixing some ray tracing issues - namely, making the outermost boundary a circle (ie, the core vessel).

**Comment by geogunow** [comment]
What is the status of this? @jtramm would be interested in using the tracking files generated from this.

**Comment by wbinventor** [comment]
A lot of the heavy lifting for this was done by @Jasmeet107 last summer and fall. A lot of things in the model were fixed by @samuelshaner, though I'm not quite sure where his version stands. @samuelshaner - what do you think opening a PR with the full model, including cross-section data?

A medium-term goal of mine is to get the OpenCG model of BEAVRS working with OpenMOC. At the moment, the only issues precluding this are:

* OpenMOC needs cell *rotations* and *translations*
* I need to get the CASMO-generated cross-sections to integrate with the OpenCG materials

I've been waiting to work on the first item until a few "barebones" features for modeling 3D geometries are released (to avoid redundancy). I'm not sure if and when this will happen, but perhaps @samuelshaner has an idea. This is of particular interest to me since I will need the full-core BEAVRS model soonish for my thesis work.

**Comment by GiudGiud** [comment]
This is now fairly easy to do using the public BEAVRS benchmark repo, OpenMC and the MGXS module to transfer cross sections.
Closing this issue.
